#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
USE_PROCD=1
START=95
STOP=10

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/nordvpn-manager-health
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/nordvpn_manager
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	/usr/libexec/nordvpn-manager reconcile >/dev/null 2>&1 || true
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger nordvpn_manager
}
